feat: UUIDs slice type with Strings() convenience method
google/uuid pull request #133
Opened 2023-10-25 15:46 UTC by dzbee

I often work with slices of UUIDs and want to include them in log messages. It is therefore convenient to be able to easily transform a slice of UUIDs into a slice of strings. In the interest of avoiding repeating code across many projects to accomplish this, I suggest defining a slice type in this project. 

This PR adds such a type and defines a convenience method `Strings()` on it.

This type additionally gives maintainers the opportunity to add further convenience methods; for instance one could implement the sort interface on this new type.

2023-10-25 15:50 UTC, bormanp requested changes

2023-10-25 15:50 UTC, bormanp commented on uuid.go
> +type UUIDs []UUID
Please add a period at the end of the sentence.

2023-10-25 15:50 UTC, bormanp commented on uuid.go
> +// Strings returns a slice of the string form of each UUID in the received slice of UUIDs
// Strings returns a string slice containing the string form of each UUID in uuids.

2023-10-25 16:55 UTC, bormanp approved these changes
Thank you for your addition to the UUID package.

2023-10-26 14:07 UTC, merged

2023-10-27 08:02 UTC, loeffel-io commented
Would love to see also the Scanner and Value interface for the UUID slice in this pkg - i could create a PR for this if there is some interest