add uuid version 6 and 7
google/uuid pull request #139
Opened 2023-11-15 15:35 UTC by it512

add uuid version6， version7

https://datatracker.ietf.org/doc/html/draft-peabody-dispatch-new-uuid-format-03#variant_and_version_fields

recommit #138

2023-11-20 17:33 UTC, bormanp requested changes

2023-11-20 17:33 UTC, bormanp commented on time.go
> +// uuid.  The time is only defined for version 1, 2 and 6, 7 UUIDs.
1, 2, 6 and 7.

2023-11-20 17:33 UTC, bormanp commented on version7.go
> +// it use NewRandomFromReader fill random bits, if error, NewV7FromReader returns Nil and an error
// On error, NewV7FromReader returns Nil and an error.

2023-11-20 17:33 UTC, bormanp commented on version7.go
> +// NewV7 use NewRandom fill random bits, if error, NewV7 returns Nil and an error
There is no need to specify the internal implementation.  Line 22 should be:

// On error, NewV7 returns Nil and an error.

2023-11-21 12:04 UTC, it512 commented
ok fix it. Thank your!
@bormanp

2023-11-23 23:49 UTC, bormanp approved these changes

2023-11-23 23:50 UTC, merged