hash.go hash error covered and linter error fixed
google/uuid pull request #71
Opened 2021-01-07 18:03 UTC by yusufpapurcu

Error covered without change function definition

2021-01-07 18:05 UTC, yusufpapurcu commented
@googlebot I signed it!

2021-01-08 18:22 UTC, pborman requested changes
These error checks are unnecessary:

```
type Hash interface {
    // Write (via the embedded io.Writer interface) adds more data to the running hash.
    // It never returns an error.
    io.Writer
```

2021-01-08 19:52 UTC, yusufpapurcu commented
So we need to add `//nolint:errcheck` because if we don't add it will fails in linting.

2021-01-15 00:26 UTC, pborman commented
Thank you. FYI, the other option is just saying `_, _ = h.Write(...)`

2021-01-15 00:27 UTC, merged